added new file - hw-11.06
SvitlanaGuba/js-homework-1 pull request #6
Opened 2024-06-11 10:13 UTC by SvitlanaGuba

added file hw-11.06

2024-06-11 10:17 UTC, SvitlanaGuba commented on cypress/e2e/hw-11.06.cy.js
> +
Питання, не спрацьовує для testData.position та testDat.type, можливо треба розписувати для кожного варіанту у випадаючому списку, як прописано нижче? Чи помилка пов'язана з використанням змінних?
        cy.get('[ng-reflect-selected="top-right"]').click();
         cy.get('[ng-reflect-selected="top-right"]').should("contain", testData1[0].position);
         cy.get('[ng-reflect-selected="top-left"]').should("contain",testData2[0].position);
        cy.get('[ng-reflect-selected="bottom-right"]').should("contain",testData3[0].position);
        cy.get('[ng-reflect-selected="bottom-left"]').should("contain", testData4[0].position);

         
         cy.get('[ng-reflect-selected="success"]').click({ force: true });
         cy.get('[ng-reflect-selected="success"]').should("contain", testData1[0].type);
         cy.get('[ng-reflect-selected="warning"]', {timeout: 20000}).select(testData2.type);
         cy.get('[ng-reflect-selected="info"]', {timeout: 20000}).select(testData3.type);
         cy.get('[ng-reflect-selected="danger"]', {timeout: 20000}).select(testData4.type);
         
         Не спрацьовує для цього коду, хоча повинно працювати
         cy.get('nb-toast[ng-reflect-toast="[object Object]"]').should('have.css', 'background', expectedResults[0].color);
        cy.get('class="title subtitle"]"]').should('contain.value', expectedResult4.title);
         cy.get('[class="message"]"]').should('contain.value', expectedResult4.content);

2024-06-11 15:10 UTC, SanitarskyiDmytro requested changes
залишив деякі коменти, але там виправлення в кожному майже рядку потрібно зробити.
Я б радив написати 1 тест для одного набору даних, а потім переробити його на параметризований

2024-06-11 15:10 UTC, SanitarskyiDmytro commented on cypress/e2e/hw-11.06.cy.js
> +     testCases.forEach(({testData, expectedResults}, index) => {
index тут зайвий

2024-06-11 15:10 UTC, SanitarskyiDmytro commented on cypress/e2e/hw-11.06.cy.js
> +     const testData1 = [
по тестовим даним є декілька пунктів які я б змінив:
1. Не має сенсу розбивати тестові дані на testData1 , testData2 і т.д., є сенс зробити одну змінну в яку скласти всі testData та expectedResults
2. Не потрібно робити testData та expectedResult масивом, якщо там тільки 1 елемент, потрібно залишити тільки сам елемент, це трішки спростить використання цих даних.

2024-06-11 15:10 UTC, SanitarskyiDmytro commented on cypress/e2e/hw-11.06.cy.js
> +     const testData1 = [
```
const testCases = [
    {
        testData: {
            position: 'top-right',
            title: 'some test1',
            content: 'some content1',
            time: '1000',
            type: 'success'
        },
        expectedResult: {
            icon: 'email1',
            title: 'some test1',
            content: 'some content1',
            color: 'rgb(40,167,69)',
            position: 'static'
        }
    },
    {
        testData: {
            position: 'top-left',
            title: 'some test2',
            content: 'some content2',
            time: '2000',
            type: 'warning'
        },
        expectedResult: {
            icon: 'email2',
            title: 'some test2',
            content: 'some content2',
            color: 'rgb(255,193,7)',
            position: 'static'
        }
    },
    {
        testData: {
            position: 'bottom-right',
            title: 'some test3',
            content: 'some content3',
            time: '3000',
            type: 'info'
        },
        expectedResult: {
            icon: 'email3',
            title: 'some test3',
            content: 'some content3',
            color: 'rgb(23,162,184)',
            position: 'static'
        }
    },
    {
        testData: {
            position: 'bottom-left',
            title: 'some test4',
            content: 'some content4',
            time: '4000',
            type: 'danger'
        },
        expectedResult: {
            icon: 'email4',
            title: 'some test4',
            content: 'some content4',
            color: 'rgb(220,53,69)',
            position: 'static'
        }
    }
];

```

2024-06-11 15:10 UTC, SanitarskyiDmytro commented on cypress/e2e/hw-11.06.cy.js
> +             cy.get('[class="title subtitle"]').should('contain.value', expectedResult[0].title);
ці рядки не працюють тому що неправильна назва у параметра expectedResult, має бути expectedResults згідно з тим як ви це визначили в параметрах

2024-06-11 15:10 UTC, SanitarskyiDmytro commented on cypress/e2e/hw-11.06.cy.js
> +             cy.get(positionSelector, {timeout: 10000}).should('have.attr', 'ng-reflect-selected', testData[0].position);
тест падає на цьому кроці через те що не знаходить елемент з таким селектором

2024-06-11 15:10 UTC, SanitarskyiDmytro commented on cypress/e2e/hw-11.06.cy.js
> +             cy.get(positionSelector, {timeout: 10000}).should('have.attr', 'ng-reflect-selected', testData[0].position);
можна так спробувати

cy.get('div.col-md-6.col-sm-12  button.select-button').eq(0).click();

2024-06-11 15:10 UTC, SanitarskyiDmytro commented on cypress/e2e/hw-11.06.cy.js
> +             cy.get(positionSelector).click({force: true});
```cy.get(`nb-option[ng-reflect-value="${testData[0].position}"]`).click();```

2024-06-13 19:16 UTC, SanitarskyiDmytro requested changes

2024-06-13 19:16 UTC, SanitarskyiDmytro commented on cypress/e2e/hw 11.06. new.cy.js
> +    testCases.forEach(({testData, expectedResultpassword}) => {
другим параметром в функції має бути `expectedResult` , а не `expectedResultpassword`

2024-06-13 19:16 UTC, SanitarskyiDmytro commented on cypress/e2e/hw 11.06. new.cy.js
> +      cy.get('nb-toastr-container nb-toast div span').should('have.text', expectedResult.title);
![image](https://github.com/SvitlanaGuba/js-homework-1/assets/43505027/9dab4ac2-f7b0-40fb-839d-d12ccf70af8a)

В тексті помилки, яку кидає сайпрес видно, що ви очікуєте що текст елемента **буде строго дорівнювати**  `some test1` , але фактично в елементі текст `Toast 2. some test1` 

Щоб виправити це можна змінити 
`.should('have.text', expectedResult.title);`
на 
`.should('contain', expectedResult.title);`

2024-06-13 19:16 UTC, SanitarskyiDmytro commented on cypress/e2e/hw 11.06. new.cy.js
> +      cy.get('nb-toast [ng-reflect-config="[object Object]"]').children().should('have.class','data-name')//icon
тут неправильний селектор і перевірка. Селектор знаходить батьківський елемент в якому немає атрибута з іконкою. 

Під ваш код можна так зробити:
```cy.get(`g[data-name=${expectedResult.icon}]`).should('be.visible')//icon```

2024-06-18 18:53 UTC, SanitarskyiDmytro approved these changes

2024-06-18 18:53 UTC, SanitarskyiDmytro commented on cypress/support/helper.js
> +            cy.get('.pagination li a').click({ multiple: true, force: true  });
так ця функція не буде знаходити товар, треба вказати на яку точно сторінку переходити. В нашому випадку це може бути кнопка зі стрілочкою ">" в пагінації

2024-06-20 10:42 UTC, merged